# -*- coding: utf-8 -*-
"""test.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jzZ6EAxY_i0XPuC8PZ9iwaftL1vq74qz
"""

#print("HOLA MUNDO; Soy Python me han llamado desde PHP");
import sys
#import os
#import json
#sys.path.append("C:\\lib\\site-packages")
#print(sys.path)
import pandas as pd
d = {'col1': [1, 2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1, 2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1], 'col2': [1, 2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1, 2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}
df = pd.DataFrame(data=d)
result=df.to_html()
print(result)